services:
  - type: web
    name: auto-filter-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: DATABASE_URL
        value: your_mongodb_url
      - key: URL
        value: https://your-render-url.onrender.com/  # <- must end with /
      - key: PORT
        value: 10000  # Render will override this anyway
      # ... (rest of your vars)
