services:
  - type: web
    name: auto-filter-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: DB_URL
        value: your_mongodb_uri
      - key: BOT_USERNAME
        value: your_bot_username
      - key: LOG_CHANNEL
        value: -100xxxxxxxxx
      - key: BIN_CHANNEL
        value: -100yyyyyyyyy
      - key: SUPPORT_GROUP
        value: -100zzzzzzzzz
      - key: PORT
        value: 10000  # Render will override this, but it's fine to include
        
